sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '123456'
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7SNpkxWMy7t8cpEgJy
    access-key-secret: 0eqsjdw3wqhNaapS7BJvk1WbO0SyeD
    bucket-name: sky-take-out-spt
